### ISSUE TITLE
Bootstrap fails with 'cannot find package' errors

### ISSUE THREAD

**Issue by aranw** [go-bootstrap/go-bootstrap#15]
During installation I get errors running godep

```
2015/05/08 09:37:50 Installing github.com/tools/godep...
2015/05/08 09:37:53 Running git init
2015/05/08 09:37:53 Running godep save
2015/05/08 09:37:53 godep: cannot find package "github.com/Sirupsen/logrus" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/Sirupsen/logrus (from $GOROOT)
	/Users/aran/Code/go/src/github.com/Sirupsen/logrus (from $GOPATH)
godep: cannot find package "github.com/carbocation/interpose" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/carbocation/interpose (from $GOROOT)
	/Users/aran/Code/go/src/github.com/carbocation/interpose (from $GOPATH)
godep: cannot find package "github.com/gorilla/context" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/gorilla/context (from $GOROOT)
	/Users/aran/Code/go/src/github.com/gorilla/context (from $GOPATH)
godep: cannot find package "github.com/gorilla/mux" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/gorilla/mux (from $GOROOT)
	/Users/aran/Code/go/src/github.com/gorilla/mux (from $GOPATH)
godep: cannot find package "github.com/gorilla/sessions" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/gorilla/sessions (from $GOROOT)
	/Users/aran/Code/go/src/github.com/gorilla/sessions (from $GOPATH)
godep: cannot find package "github.com/jmoiron/sqlx" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/jmoiron/sqlx (from $GOROOT)
	/Users/aran/Code/go/src/github.com/jmoiron/sqlx (from $GOPATH)
godep: cannot find package "github.com/stretchr/graceful" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/github.com/stretchr/graceful (from $GOROOT)
	/Users/aran/Code/go/src/github.com/stretchr/graceful (from $GOPATH)
godep: cannot find package "golang.org/x/crypto/bcrypt" in any of:
	/usr/local/Cellar/go/1.4.2/libexec/src/golang.org/x/crypto/bcrypt (from $GOROOT)
	/Users/aran/Code/go/src/golang.org/x/crypto/bcrypt (from $GOPATH)
godep: error loading dependencies
exit status 1
```

**Comment by awsh** [comment]
Can confirm. I get the same errors.

**Comment by dfwmountainbiker** [comment]
Same, i had to individually go get them

**Comment by didip** [comment]
Ugh, I forgot to commit the generated Godeps directory. It should be fixed now.

**Comment by timscott** [comment]
Just now did ```git pull``` and verified I have commit ```32acedbb9480f9ff8d81d658b522b4f2920cf0be``` but still getting this error.

**Comment by dfwmountainbiker** [comment]
@timscott I had previously had the error (yesterday). Did a fresh pull (del rm -rf of the project, and then go get) and re-ran and had no issues. You may try that.

**Comment by timscott** [comment]
@dfwmountainbiker Thanks. Tried it. Same error.

**Comment by didip** [comment]
@timscott @dfwmountainbiker Can you both do a fresh pull and try again?

I had previously thought to freeze the dependencies in `/Godeps` directory before hand. But then I changed my mind because the `/Godeps` directory can be stale.

**Comment by timscott** [comment]
Just to be specific I did this:

```bash
cd $GOPATH/src/github.com
rm -rf go-bootstrap
go get github.com/go-bootstrap/go-bootstrap
cd go-bootstrap/go-bootstrap
go run main.go -dir github.com/timscott/hello-web
```
Now I get a different error:

``` bash
2015/05/08 10:10:11 Creating /Users/tscott/code/go/src/github.com/timscott/hello-web...
2015/05/08 10:10:11 Copying a blank project to /Users/tscott/code/go/src/github.com/timscott/hello-web...
2015/05/08 10:10:11 Replacing placeholder variables on timscott/hello-web...
2015/05/08 10:10:11 Creating a database named hello-web...
2015/05/08 10:10:11 Unable to create PostgreSQL database: hello-web
2015/05/08 10:10:11 Creating a database named hello-web-test...
2015/05/08 10:10:11 Unable to create PostgreSQL database: hello-web-test
2015/05/08 10:10:11 Installing github.com/mattes/migrate...
2015/05/08 10:10:11 Running database migrations on postgres://tscott@localhost:5432/hello-web?sslmode=disable...
2015/05/08 10:10:11 Running database migrations on postgres://tscott@localhost:5432/hello-web-test?sslmode=disable...
2015/05/08 10:10:11 Running go get ./...
2015/05/08 10:10:25 Installing github.com/tools/godep...
2015/05/08 10:10:25 Running git init
2015/05/08 10:10:25 Running godep save
2015/05/08 10:10:26 Running godep go test ./...
2015/05/08 10:10:27 # github.com/timscott/hello-web/dal
dal/base_test.go:8:2: cannot find package "github.com/satori/go.uuid" in any of:
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/github.com/satori/go.uuid (from $GOROOT)
	/Users/tscott/code/go/src/github.com/timscott/hello-web/Godeps/_workspace/src/github.com/satori/go.uuid (from $GOPATH)
	/Users/tscott/code/go/src/github.com/satori/go.uuid
FAIL	github.com/timscott/hello-web/dal [setup failed]
?   	github.com/timscott/hello-web	[no test files]
?   	github.com/timscott/hello-web/handlers	[no test files]
ok  	github.com/timscott/hello-web/libenv	0.009s
ok  	github.com/timscott/hello-web/libhttp	0.010s
?   	github.com/timscott/hello-web/libunix	[no test files]
?   	github.com/timscott/hello-web/middlewares	[no test files]
godep: go exit status 1
```

**Comment by didip** [comment]
Ah, test dependencies are not vendored. Give me a sec, writing a fix.

**Comment by didip** [comment]
I just pushed a fix: https://github.com/go-bootstrap/go-bootstrap/commit/3b85628454388f615f3ba2948e979ca79dabf34b

@timscott Can you confirmed that it is working?

**Comment by timscott** [comment]
Same error, slightly different output:

```bash
> go run main.go -dir github.com/timscott/hello-web
2015/05/08 10:22:50 Creating /Users/tscott/code/go/src/github.com/timscott/hello-web...
2015/05/08 10:22:50 Copying a blank project to /Users/tscott/code/go/src/github.com/timscott/hello-web...
2015/05/08 10:22:50 Replacing placeholder variables on timscott/hello-web...
2015/05/08 10:22:50 Creating a database named hello-web...
2015/05/08 10:22:50 Unable to create PostgreSQL database: hello-web
2015/05/08 10:22:50 Creating a database named hello-web-test...
2015/05/08 10:22:50 Unable to create PostgreSQL database: hello-web-test
2015/05/08 10:22:50 Installing github.com/mattes/migrate...
2015/05/08 10:22:50 Running database migrations on postgres://tscott@localhost:5432/hello-web?sslmode=disable...
2015/05/08 10:22:51 Running database migrations on postgres://tscott@localhost:5432/hello-web-test?sslmode=disable...
2015/05/08 10:22:51 Running go get ./...
2015/05/08 10:22:52 Installing github.com/tools/godep...
2015/05/08 10:22:52 Running git init
2015/05/08 10:22:52 Running godep save ./...
2015/05/08 10:22:52 godep: cannot find package "github.com/satori/go.uuid" in any of:
	/usr/local/Cellar/go/1.3.3/libexec/src/pkg/github.com/satori/go.uuid (from $GOROOT)
	/Users/tscott/code/go/src/github.com/satori/go.uuid (from $GOPATH)
godep: error loading packages
exit status 1
```

**Comment by didip** [comment]
Hm... I had expected that go get ./... also installs testing dependencies.
If it's not too much to ask, can you do me a favor and try installing missing dependencies by hand, and tell me which packages are missing?
I'll add them as part of the generator process.

**Comment by didip** [comment]
I've added `github.com/satori/go.uuid` as part of install process.

**Comment by timscott** [comment]
Now ```go run main.go -dir github.com/timscott/hello-web``` completes without errors.

**Comment by didip** [comment]
Awesome! Thank you for your patience.

**Comment by didip** [comment]
I decided to remove satori.uuid dependency. It is only used for testing. Ref: https://github.com/go-bootstrap/go-bootstrap/commit/56c49d4bc79e368bff3b5efd8ab20abb585fb57d
